# -*- coding: utf-8 -*-
"""Primeira_questão_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIBTgERHzgB0U309NlxGjSdk6MOnak6k

1a questão a):
"""

print("Digite a quantidade de pratos na pilha\n")
pratos=int(input())
pilha=[]
desempilhar = 0
#Quantidade de pratos na pilha
for i in range(pratos):
  pilha.append(f"Prato {i}")
print(f'Na pilha tem {len(pilha)} pratos\n')

#desempilhar os pratos
print("Digite 'D' caso queira tirar 1 prato da pilha ou 'E' para encerrar o programa\n")
while(1):
  D = input()
  if (D == 'D' ):
    if(len(pilha) == 0):
      print("Sem pratos na pilha")
      break
    pilha.pop(-1)
  elif(D == 'E'):
    break

print(f"Sobraram {len(pilha)} pratos na pilha\n")
print(f"A pilha está disposta da seguinte forma: {pilha}")

"""1a questão b):"""

print("Digite a quantidade de pessoas na fila")
pessoas=int(input())
fila=[]
saiu = 0
#Quantidade de pessoas na fila
for i in range(pessoas):
  fila.append(f'pessoa {i}')
print(f"\nNa fila tem {len(fila)} pessoas")

#sair da fila
print("\nDigite 'S' caso queira tirar 1 pessoa da fila ou 'E' para encerrar o programa")
while(1):
  S = input()
  if (S == 'S' ):
    if(len(fila) == 0):
      print("Sem pessoas na fila\n")
      break
    fila.pop(0)
  elif(S == 'E'):
    break

print(f"\nSobraram {len(fila)} pessoas na fila\n")
print(f"A fila está disposta da seguinte forma: {fila}")