# -*- coding: utf-8 -*-
"""Quarta_questão_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIBTgERHzgB0U309NlxGjSdk6MOnak6k

4a questão:
"""

lista = []
num5 = 0
num3 = 0
qpar = []
qimpar = []
for i in range(10):
  lista.append(int(input("Digite um número de 1 a 10: ")))

tupla = tuple(lista)
for i in tupla:
  if(i == 5):
    num5+=1
    if(i == 5 and num5 > 1):
          continue
  elif(i == 3):
    num3 = tupla.index(i)
  elif(i%2 == 0):
    qpar.append(i)
  if(i%2 != 0):
      qimpar.append(i)                    
pares = set(qpar)
impares = set(qimpar)
print(f'''\nO número 5 foi digitado {num5} vezes
A posição do número 3 é: {num3}
Tiveram {len(pares)} números pares, que foram: {pares}
Tiveram {len(impares)} números impares, que foram: {impares}''')