# -*- coding: utf-8 -*-
"""Quinta questão

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-5lp1urFv5SYIwuhHX1Ef0Edck2wkIl

Letra A)
"""

modelos = []
consumo = []
litros = []
for i in range(10):
   modelos.append(input("marca= "))
   consumo.append(int(input("consumo desta marca = ")))

print(f"O modelo mais econômico é {modelos[consumo.index(max(consumo))]}\n")

"""Letra B)"""

x = (int(input("Valor de x: ")))

for i in range(10):
  litros.append(x/consumo[i])

for i in range(10):
   print(f'''A marca {modelos[i]} em {x}km terá um consumo de {litros[i]} litros''')

"""Letra C)"""

custo = []

for i in range(10):
  custo.append(5.5*litros[i])

for i in range(10):
  print(f'''A marca {modelos[i]} em {x}km terá um custo de R${custo[i]}''')