# -*- coding: utf-8 -*-
"""Segunda_questão_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIBTgERHzgB0U309NlxGjSdk6MOnak6k

2a questão:
"""

emprestimo = []
i=0
while(1):
  print("Se quiser saber se o empréstimo bancário será aprovado, digite 1. Caso não, digite qualquer outra tecla")
  a = input()
  if(a == '1'):
    i=0
    print("\nDigite o valor da casa a comprar")
    emprestimo.append(float(input("Valor da casa: R$")))
    i=+1
    print("\nDigite o Salário")
    emprestimo.append(float(input("Salário: R$")))
    i=+1
    print("\nDigite a quantidade de anos a pagar")
    emprestimo.append(float(input("Anos a pagar: ")))

    prest= emprestimo[0]/(emprestimo[2]*12)
    if(prest > 0.3*emprestimo[1]):
      print("\nEmpréstimo não aprovado!\n")
    else:
      print("\nEmpréstimo aprovado!\n")
    
    emprestimo.pop(0)
    emprestimo.pop(0)
    emprestimo.pop(0)
    
  else:
    break