# -*- coding: utf-8 -*-
"""Sexta_questão

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-5lp1urFv5SYIwuhHX1Ef0Edck2wkIl
"""

lista1 = [] 
lista2 = []

for i in range(5):
  lista1.append(input(f"indice {i} da Lista1= "))
  lista2.append(input(f"indice {i} da Lista2= "))

print (f"Lista1: {lista1}, que contém {len(lista1)} elementos") 
print (f"Lista2: {lista2}, que contém {len(lista2)} elementos")
lista3 = lista1 + lista2 
lista3[::2] = lista1 
lista3[1::2] = lista2 
print (f"Lista3: {lista3}, que contém {len(lista3)} elementos")