# -*- coding: utf-8 -*-
"""Sétima_questão

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G-5lp1urFv5SYIwuhHX1Ef0Edck2wkIl
"""

mult=0
primos = []
x_primos = int(input("x= "))
for n in range (2, 200):
  for count in range(2,n):
      if (n % count == 0):
          print(f"n = {n}")
          #print("Múltiplo de",count)
          mult += 1

  if(mult==0):
      print(f"{n} é primo")
      primos.append(n)

  else:
    mult = 0    

  if(len(primos)==x_primos):
    break
print(primos)