# -*- coding: utf-8 -*-
"""Terceira_questão_python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bIBTgERHzgB0U309NlxGjSdk6MOnak6k

3a questão:
"""

crime = []

crime.append(input("Telefonou para a vítima?: "))
crime.append(input("Esteve no local do crime?: "))
crime.append(input("mora perto da vitima?: "))
crime.append(input("Devia para a vítima?: "))
crime.append(input("Já trabalhou com a vítima?: "))

criminoso = 0

for i in crime:
  if(i == 'sim'):
      criminoso +=1

if(criminoso == 2):
  print("\nSuspeita")
elif(criminoso >2 and criminoso <= 4):
  print("\nCúmplice")
elif(criminoso > 4):
  print("\nAssasino")
else:
  print("\nInocente")